apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k-s
manifests:
  rawYaml:
    - ingress.yaml
    - mongodb-configmap.yaml
    - mongodb-deployment.yaml
    - mongodb-secret.yaml
    - privileges.yaml
