spring:
  application:
    name: organization

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0 # Adjust to trace all requests (set lower for sampling)

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all management endpoints
  endpoint:
    health:
      show-details: ALWAYS
