apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: admin
          image: piomin/admin
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_APPLICATION_NAME
              value: "admin"
            - name: SPRING_BOOT_ADMIN_DISCOVERY_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED
              value: "true"
            - name: SPRING_BOOT_ADMIN_DISCOVERY_CONVERTER_HEALTH-URL
              value: "${metadata.labels['app']}://${metadata.ipAddress}:8080/actuator/health"
            - name: SPRING_BOOT_ADMIN_MONITORING_SERVICES
              value: "employee,department,organization"
